# Generated by Django 3.1.3 on 2020-11-20 06:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_auto_20201119_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
